### ISSUE TITLE
name at the top?

### ISSUE THREAD

**Issue by elahi** [gadamc/soundeffectsapp#1]
and contact info?

https://github.com/gadamc/soundeffectsapp/blob/8fa7e6e740a483a0f61dd7dac6ddacb82be129c4/soundeffectsapp/views.py#L1

**Comment by gadamc** [comment]
@elahi - can you explain again your comment here? What would you like me to add?

**Comment by elahi** [comment]
Sorry, vague comment.  It may be useful to add your name and contact info to the top of your readme.  But your call.
